package ie.ucc.bis.supportinglife.reference;

public enum CcmClassificationsEnum {
	CCM_COUGH_FOR_21_DAYS_OR_MORE_CLASSIFICATION, 
	CCM_DIARRHOEA_FOR_14_DAYS_OR_MORE_CLASSIFICATION, 
	CCM_BLOOD_IN_STOOL_CLASSIFICATION, 
	CCM_DIARRHOEA_LESS_THAN_14_DAYS_AND_NO_BLOOD_IN_STOOL_CLASSIFICATION, 
	CCM_FEVER_FOR_LAST_7_DAYS_CLASSIFICATION, 
	CCM_FEVER_FOR_LESS_THAN_7_DAYS_CLASSIFICATION,
	CCM_CONVULSIONS_CLASSIFICATION, 
	CCM_NOT_ABLE_TO_DRINK_OR_FEED_ANYTHING_CLASSIFICATION, 
	CCM_VOMITS_EVERYTHING_CLASSIFICATION,
	CCM_RED_EYE_FOR_4_DAYS_OR_MORE_CLASSIFICATION, 
	CCM_RED_EYE_WITH_VISUAL_PROBLEMS_CLASSIFICATION, 
	CCM_RED_EYE_LESS_THAN_4_DAYS_CLASSIFICATION,
	CCM_OTHER_PROBLEM_CLASSIFICATION,
	CCM_CHEST_INDRAWING_CLASSIFICATION,
	CCM_FAST_BREATHING_CLASSIFICATION,
	CCM_FAST_BREATHING_AND_DANGER_SIGN_CLASSIFICATION,
	CCM_VERY_SLEEPY_OR_UNCONSCIOUS_CLASSIFICATION,
	CCM_PALMAR_PALLOR_CLASSIFICATION,
	CCM_RED_ON_MUAC_TAPE_CLASSIFICATION,
	CCM_SWELLING_OF_BOTH_FEET_CLASSIFICATION;

}
